version: '3.8'

services:
    springboot:
        build: .
        container_name: ShrysthContainer
        
        environment:
            SPRING_APPLICATION_NAME: Shrysth
            SERVER_PORT: 5000
            SPRING_MAIL_HOST: smtp.gmail.com
            SPRING_MAIL_PORT: 587
            SPRING_MAIL_USERNAME: siddshrysth@gmail.com
            SPRING_MAIL_PASSWORD: okan vqif lslm okeq
            SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
            SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
            SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: true
        ports:
        - "5000:5000"
